# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Haliski
email: matt@leavingharbor.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Matt Haliski and I code stuff. You can find me wandering around the
  streets of Seattle, WA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matthaliski.com" # the base hostname & protocol for your site
twitter_username: matthaliski
github_username:  matthaliski

# Build settings
markdown: kramdown

# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# Outputting
# permalink: /:year/:month/:day/:title

# Site Version
# version: 0.1.0

# Pagination
# paginate: 10
# paginate_path: "/blog/:num/"
